CREATE TABLE `TB_STG_MAPA_SPOOLS` (
	`CODIGO` BIGINT AUTO_INCREMENT,
    `SERVIÇO` nvarchar(255) NOT NULL,
    `LOCAL FABRICAÇÃO` nvarchar(255) NOT NULL,
    `TR / CJ` nvarchar(255) NOT NULL,
    `ISOMÉTRICO` nvarchar(255) NOT NULL,
    `SPOOL` nvarchar(255) NOT NULL,
    `REV` nvarchar(255) NOT NULL,
    `ESPEC` nvarchar(255) NOT NULL,
    `ÁREA` nvarchar(255) NOT NULL,
    `MATERIAL` nvarchar(255) NOT NULL,
    `PROG FAB` nvarchar(255),
    `EXECUTANTE FAB` nvarchar(255),
    `DATA PROG FAB` datetime,
    `REQ FAB` nvarchar(255),
    `PROG MONT` nvarchar(255),
    `DATA PROG MONT` datetime,
    `REQ MONT` nvarchar(255),
    `ROMANEIOS` nvarchar(255),
    `DATA ÚLTIMO ROM` datetime,
    `DIÂM MIN` nvarchar(255),
    `DIÂM MAX` nvarchar(255),
    `LINHA` nvarchar(255) NOT NULL,
    `FLUÍDO` nvarchar(255) NOT NULL,
    `CLASSE PRESSÃO` nvarchar(255),
    `STH` nvarchar(255),
    `CORTE/BISEL` datetime,
    `PESO` float,
    `JUNTAS PIPE` float,
    `JUNTAS CAMPO` float,
    `TOTAL JUNTAS` float,
    `LIB VA FAB` nvarchar(255),
    `LIB SOLDA FAB` nvarchar(255),
    `LIB VS FAB` nvarchar(255),
    `LIB LP/PM FAB` nvarchar(255),
    `LIB RX/US FAB` nvarchar(255),
    `LIB VA MONT` nvarchar(255),
    `LIB SOLDA MONT` nvarchar(255),
    `LIB VS MONT` nvarchar(255),
    `LIB LP/PM MONT` nvarchar(255),
    `LIB RX/US MONT` nvarchar(255),
    `FABRICAÇÃO` nvarchar(255),
    `MONTAGEM` nvarchar(255),
    `OBSERVAÇÃO DO SPOOL` nvarchar(255),
    `OBSERVAÇÃO DO ISOMÉTRICO` nvarchar(255),
    `STATUS` nvarchar(255),
    `DATA DIM FAB` datetime,
    `REL DMF` nvarchar(255),
    `INSP DMF` nvarchar(255),
    `DATA DIM CAMPO` datetime,
    `REL DMC` nvarchar(255),
    `INSP DMC` nvarchar(255),
    `Rel TH Fab` nvarchar(255),
    `Rel TH` nvarchar(255),
    `COND PINT` nvarchar(255),
    `REL PINT 1 F` nvarchar(255),
    `DATA 1ª F` datetime,
    `REL PINT 2 F` nvarchar(255),
    `DATA 2ª F` datetime,
    `REL PINT 1 A` nvarchar(255),
    `DATA 1ª A` datetime,
    `REL PINT 2 A` nvarchar(255),
    `DATA 2ª A` datetime,
    `DECAP FAB` nvarchar(255),
    `RETOQUE / DECAP MONT` nvarchar(255),
    `REL REVEST` nvarchar(255),
    `REL ISOLAMENTO` nvarchar(255),
    `Data Cadastro` datetime,
    `ID_ISOMETRICO` float,
    `ID_SPOOL` float,
	PRIMARY KEY (codigo)
)