CREATE TABLE `TB_STG_MAPA_JUNTAS` (
	`CODIGO` BIGINT AUTO_INCREMENT,
    `CONTRATO` nvarchar(255),
    `SERVIÇO` nvarchar(255),
    `CARACTERÍSTICA` nvarchar(255),
    `LOCAL FAB` nvarchar(255),
    `ISOMÉTRICO` nvarchar(255),
    `REV` nvarchar(255),
    `ESPEC` nvarchar(255),
    `ÁREA / UNID` nvarchar(255),
    `SPOOL` nvarchar(255),
    `JUNTA` nvarchar(255),
    `DIAM` nvarchar(255),
    `PERIMETRO` float,
    `SCH` nvarchar(255),
    `ESPESSURA` float,
    `TIPO` nvarchar(255),
    `CONFIG` nvarchar(255),
    `PLANEJ ENSAIO` nvarchar(255),
    `MATERIAL` nvarchar(255),
    `PN` nvarchar(255),
    `CLASSE` nvarchar(255),
    `LOCAL` nvarchar(255),
    `LINHA` nvarchar(255),
    `FLUÍDO` nvarchar(255),
    `CLASSE DE PRESSÃO` nvarchar(255),
    `LINHA + SPOOL` nvarchar(255),
    `CORTE/BISEL` datetime,
    `ACOP PLANEJ` datetime,
    `SOLDA PLANEJ` datetime,
    `STATUS` nvarchar(255),
    `PROG RX EMITIDAS` nvarchar(255),
    `LOTE LP/PM` nvarchar(255),
    `LOTE RX/US RAIZ` nvarchar(255),
    `LOTE RX/US ENCH` nvarchar(255),
    `DATA SOLDA` datetime,
    `IEIS` nvarchar(255),
    `SINETE RAIZ` nvarchar(255),
    `SINETE ENCH` nvarchar(255),
    `CICLO` nvarchar(255),
    `DATA VA` datetime,
    `REL VA` nvarchar(255),
    `INSP VA` nvarchar(255),
    `REL VS` nvarchar(255),
    `DATA VS` datetime,
    `INSP VS` nvarchar(255),
    `DATA LPPM BISEL` datetime,
    `REL LPPM BISEL` nvarchar(255),
    `INSP LPPM BISEL` nvarchar(255),
    `DATA LPPM RAIZ` datetime,
    `REL LPPM RAIZ` nvarchar(255),
    `INSP LPPM RAIZ` nvarchar(255),
    `DATA LPPM` datetime,
    `REL LPPM` nvarchar(255),
    `INSP LPPM` nvarchar(255),
    `DATA ES` datetime,
    `REL ES` nvarchar(255),
    `INSP ES` nvarchar(255),
    `DATA TT` datetime,
    `REL TT` nvarchar(255),
    `INSP TT` nvarchar(255),
    `DATA LPPMTT` datetime,
    `REL LPPMTT` nvarchar(255),
    `INSP LPPMTT` nvarchar(255),
    `DATA RX/US` datetime,
    `REL RX/US` nvarchar(255),
    `INSP RX/US` nvarchar(255),
    `REPARO` nvarchar(255),
    `FILMES REP RX` nvarchar(255),
    `COMP REP RX/US` nvarchar(255),
    `DATA ACETONA` datetime,
    `REL ACETONA` nvarchar(255),
    `DATA DU` datetime,
    `REL DU` nvarchar(255),
    `INSP DU` nvarchar(255),
    `SOP` nvarchar(255),
    `STH` nvarchar(255),
    `REL TH` nvarchar(255),
    `DATA TH` datetime,
    `REL DIM FAB` nvarchar(255),
    `DATA DIM FAB` datetime,
    `REL DIM CAMPO` nvarchar(255),
    `DATA DIM CAMPO` datetime,
    `REL PMI` nvarchar(255),
    `DATA PMI` datetime,
    `CÓDIGO MATERIAL 1` nvarchar(255),
    `CÓDIGO MATERIAL 2` nvarchar(255),
    `IDENT MATERIAL 1` nvarchar(255),
    `IDENT MATERIAL 2` nvarchar(255),
    `OBSERVAÇÃO JUNTA` nvarchar(255),
    `OBSERVAÇÃO SPOOL` nvarchar(255),
    `JUNTAATIVA` nvarchar(255),
    `DATA_CADASTRO` datetime,
    `ID_JUNTA` float,
    `ID_SPOOL` float,
    `ID_ISOMETRICO` float,
	PRIMARY KEY (CODIGO)
)